import { Category } from './category.model.js';
import { Certificate } from './certificate.model.js';
import { Course } from './course.model.js';
import { CourseModule } from './course-module.model.js';
import { Enrollment } from './enrollment.model.js';
import { InstructorProfile } from './instructor-profile.model.js';
import { Lesson } from './lesson.model.js';
import { LessonProgress } from './lesson-progress.model.js';
import { Notification } from './notification.model.js';
import { Quiz } from './quiz.model.js';
import { QuizAttempt } from './quiz-attempt.model.js';
import { QuizOption } from './quiz-option.model.js';
import { QuizQuestion } from './quiz-question.model.js';
import { Review } from './review.model.js';
import { User } from './user.model.js';

User.hasMany(Course, { foreignKey: 'instructorId', as: 'courses', onDelete: 'RESTRICT' });
Course.belongsTo(User, { foreignKey: 'instructorId', as: 'instructor' });
Category.hasMany(Course, { foreignKey: 'categoryId', as: 'courses', onDelete: 'RESTRICT' });
Course.belongsTo(Category, { foreignKey: 'categoryId', as: 'category' });
Course.hasMany(CourseModule, { foreignKey: 'courseId', as: 'modules', onDelete: 'CASCADE' });
CourseModule.belongsTo(Course, { foreignKey: 'courseId', as: 'course' });
CourseModule.hasMany(Lesson, { foreignKey: 'moduleId', as: 'lessons', onDelete: 'CASCADE' });
Lesson.belongsTo(CourseModule, { foreignKey: 'moduleId', as: 'module' });
InstructorProfile.hasMany(Course, { foreignKey: 'instructorId', sourceKey: 'userId', as: 'courses' });
User.hasMany(Enrollment, { foreignKey: 'studentId', as: 'enrollments', onDelete: 'CASCADE' });
Enrollment.belongsTo(User, { foreignKey: 'studentId', as: 'student' });
Course.hasMany(Enrollment, { foreignKey: 'courseId', as: 'enrollments', onDelete: 'CASCADE' });
Enrollment.belongsTo(Course, { foreignKey: 'courseId', as: 'course' });
Enrollment.hasMany(LessonProgress, { foreignKey: 'enrollmentId', as: 'lessonProgress', onDelete: 'CASCADE' });
LessonProgress.belongsTo(Enrollment, { foreignKey: 'enrollmentId', as: 'enrollment' });
Lesson.hasMany(LessonProgress, { foreignKey: 'lessonId', as: 'progress', onDelete: 'CASCADE' });
LessonProgress.belongsTo(Lesson, { foreignKey: 'lessonId', as: 'lesson' });
Course.hasMany(Quiz, { foreignKey: 'courseId', as: 'quizzes', onDelete: 'CASCADE' });
Quiz.belongsTo(Course, { foreignKey: 'courseId', as: 'course' });
Quiz.hasMany(QuizQuestion, { foreignKey: 'quizId', as: 'questions', onDelete: 'CASCADE' });
QuizQuestion.belongsTo(Quiz, { foreignKey: 'quizId', as: 'quiz' });
QuizQuestion.hasMany(QuizOption, { foreignKey: 'questionId', as: 'options', onDelete: 'CASCADE' });
QuizOption.belongsTo(QuizQuestion, { foreignKey: 'questionId', as: 'question' });
Quiz.hasMany(QuizAttempt, { foreignKey: 'quizId', as: 'attempts', onDelete: 'CASCADE' });
QuizAttempt.belongsTo(Quiz, { foreignKey: 'quizId', as: 'quiz' });
User.hasMany(QuizAttempt, { foreignKey: 'studentId', as: 'quizAttempts', onDelete: 'CASCADE' });
QuizAttempt.belongsTo(User, { foreignKey: 'studentId', as: 'student' });
Enrollment.hasOne(Certificate, { foreignKey: 'enrollmentId', as: 'certificate', onDelete: 'CASCADE' });
Certificate.belongsTo(Enrollment, { foreignKey: 'enrollmentId', as: 'enrollment' });
User.hasMany(Certificate, { foreignKey: 'studentId', as: 'certificates', onDelete: 'CASCADE' });
Certificate.belongsTo(User, { foreignKey: 'studentId', as: 'student' });
Course.hasMany(Certificate, { foreignKey: 'courseId', as: 'certificates', onDelete: 'CASCADE' });
Certificate.belongsTo(Course, { foreignKey: 'courseId', as: 'course' });
User.hasMany(Review, { foreignKey: 'studentId', as: 'reviews', onDelete: 'CASCADE' });
Review.belongsTo(User, { foreignKey: 'studentId', as: 'student' });
Course.hasMany(Review, { foreignKey: 'courseId', as: 'reviews', onDelete: 'CASCADE' });
Review.belongsTo(Course, { foreignKey: 'courseId', as: 'course' });
User.hasMany(Notification, { foreignKey: 'userId', as: 'notifications', onDelete: 'CASCADE' });
Notification.belongsTo(User, { foreignKey: 'userId', as: 'user' });
