import { useAuth } from '../context/AuthContext';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { instructorApi, catalogApi } from '../api/endpoints';
import { ActionForm, Field, Page, inputClass, text, slugify } from '../components/Forms';
import { ErrorState, LoadingState } from '../components/State';
import type { Course, CourseModule, Lesson, Quiz } from '../types/api';

export function CourseEditorPage() {
  const { user } = useAuth();
  const { courseId } = useParams(); const id = Number(courseId); const navigate = useNavigate(); const client = useQueryClient();
  const validId = Number.isSafeInteger(id) && id > 0;
  const course = useQuery({ queryKey: ['workspace', id], queryFn: () => instructorApi.course(id).then(r => r.data.data), enabled: validId });
  const categories = useQuery({ queryKey: ['categories'], queryFn: () => catalogApi.categories().then(r => r.data.data) });
  const refresh = () => { void client.invalidateQueries({ queryKey: ['workspace', id] }); void client.invalidateQueries({ queryKey: ['instructor-courses'] }); };
  if (courseId !== undefined && !validId) return <ErrorState message="This course could not be found." />;
  if (course.isLoading || categories.isLoading) return <LoadingState />;
  if (course.isError || categories.isError) return <ErrorState />;
  if (courseId !== undefined && !course.data) return <ErrorState message="This course could not be found." />;
  const item = course.data; const editable = user?.role === 'instructor' && (!item || ['draft', 'rejected'].includes(item.status));
  return <Page title={item ? item.title : 'Create a course'}><Link to="/dashboard">Back to dashboard</Link>{item && <p>Status: {item.status}</p>}
    {editable ? <><ActionForm key={item?.id ?? 'new'} label={item ? 'Save course' : 'Create course'} submit={async data => {
      const body = { title: text(data, 'title'), slug: text(data, 'slug') || slugify(text(data, 'title')), categoryId: Number(data.get('categoryId')), shortDescription: text(data, 'shortDescription'), description: text(data, 'description'), level: text(data, 'level') };
      if (item) { await instructorApi.updateCourse(id, body); refresh(); } else { const response = await instructorApi.createCourse(body); await client.invalidateQueries({ queryKey: ['instructor-courses'] }); navigate(`/instructor/courses/${response.data.data.id}`); }
    }}><Field name="title" label="Course title (at least 3 characters)" value={item?.title} /><Field name="slug" label="URL slug (optional when creating)" value={item?.slug} required={false} /><Field name="shortDescription" label="Summary (at least 10 characters)" value={item?.shortDescription} /><Field name="description" label="Description (at least 20 characters)" type="textarea" value={item?.description} /><label>Category<select className={inputClass} name="categoryId" defaultValue={item?.categoryId} required>{categories.data?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Level<select className={inputClass} name="level" defaultValue={item?.level ?? 'beginner'}>{['beginner', 'intermediate', 'advanced'].map(level => <option key={level}>{level}</option>)}</select></label></ActionForm>
    {item && <><h2 className="text-3xl">Modules and lessons</h2>{[...(item.modules ?? [])].sort((a,b) => a.position-b.position).map(module => <ModuleEditor key={module.id} module={module} refresh={refresh} />)}<ActionForm label="Add module" onDone={refresh} submit={data => instructorApi.createModule(id, { title: text(data, 'title'), description: text(data, 'description'), position: Number(data.get('position')) })}><Field name="title" label="Module title" /><Field name="description" label="Module description" required={false} /><Field name="position" label="Position" type="number" value={Math.max(0,...(item.modules ?? []).map(m => m.position))+1} /></ActionForm><h2 className="text-3xl">Quizzes</h2>{item.quizzes?.map(quiz => <QuizEditor key={quiz.id} quiz={quiz} refresh={refresh} />)}<ActionForm label="Create quiz" onDone={refresh} submit={data => instructorApi.createQuiz(id, { title: text(data, 'title'), passingPercentage: Number(data.get('passingPercentage')) })}><Field name="title" label="Quiz title" /><Field name="passingPercentage" label="Passing percentage (1-100)" type="number" value={70} /></ActionForm><ActionForm label="Submit for admin review" onDone={refresh} submit={() => instructorApi.submitCourse(id)}><p>Finish your lessons and publish any quizzes before submitting. Submitted courses are locked for review.</p></ActionForm></>}
    </> : <CourseOutline course={item!} />}</Page>;
}
function ModuleEditor({ module, refresh }: { module: CourseModule; refresh: () => void }) { return <details className="border p-4" open><summary className="text-2xl">{module.title}</summary><ActionForm onDone={refresh} submit={data => instructorApi.updateModule(module.id, { title: text(data,'title'), description: text(data,'description'), position: Number(data.get('position')) })}><Field name="title" label="Module title" value={module.title} /><Field name="description" label="Description" value={module.description ?? ''} required={false} /><Field name="position" label="Position" type="number" value={module.position} /></ActionForm>{[...(module.lessons ?? [])].sort((a,b) => a.position-b.position).map(lesson => <LessonEditor key={lesson.id} moduleId={module.id} lesson={lesson} refresh={refresh} />)}<LessonEditor moduleId={module.id} refresh={refresh} position={Math.max(0,...(module.lessons ?? []).map(l => l.position))+1} /><ActionForm label="Delete module and its lessons" onDone={refresh} submit={() => instructorApi.deleteModule(module.id)}><label><input type="checkbox" required /> Confirm deletion of this module and all its lessons</label></ActionForm></details>; }
function LessonEditor({ moduleId, lesson, refresh, position }: { moduleId: number; lesson?: Lesson; refresh: () => void; position?: number }) { return <details className="my-3 border p-4"><summary>{lesson?.title ?? 'Add lesson'}</summary><ActionForm label={lesson ? 'Save lesson' : 'Add lesson'} onDone={refresh} submit={data => { const body = { title: text(data,'title'), content: text(data,'content'), videoUrl: text(data,'videoUrl') || null, position: Number(data.get('position')), durationMinutes: Number(data.get('durationMinutes')) || null, isPreview: data.get('isPreview') === 'on' }; return lesson ? instructorApi.updateLesson(lesson.id, body) : instructorApi.createLesson(moduleId, body); }}><Field name="title" label="Lesson title" value={lesson?.title} /><Field name="content" label="Lesson content" type="textarea" value={lesson?.content} /><Field name="videoUrl" label="Video URL (optional)" type="url" value={lesson?.videoUrl ?? ''} required={false} /><Field name="durationMinutes" label="Duration in minutes" type="number" value={lesson?.durationMinutes ?? ''} required={false} /><Field name="position" label="Position" type="number" value={lesson?.position ?? position} /><label><input type="checkbox" name="isPreview" defaultChecked={lesson?.isPreview} /> Allow public preview</label></ActionForm>{lesson && <ActionForm label="Delete lesson" onDone={refresh} submit={() => instructorApi.deleteLesson(lesson.id)}><label><input type="checkbox" required /> Confirm lesson deletion</label></ActionForm>}</details>; }
function QuizEditor({ quiz, refresh }: { quiz: Quiz; refresh: () => void }) { return <details className="border p-4"><summary>{quiz.title} - {quiz.isPublished ? 'Published' : 'Draft'}</summary>{quiz.questions?.map(q => <div key={q.id} className="p-3"><p>{q.questionText}</p>{q.options.map(o => <p key={o.id}>{o.isCorrect ? 'Correct: ' : ''}{o.optionText}</p>)}</div>)}<ActionForm label="Add question" onDone={refresh} submit={data => instructorApi.addQuestion(quiz.id, { questionText: text(data,'questionText'), position: Number(data.get('position')), points: 1, options: [1,2,3,4].filter(n => text(data, `option${n}`)).map(n => ({ optionText: text(data, `option${n}`), position: n, isCorrect: Number(data.get('correct')) === n })) })}><Field name="questionText" label="Question" /><Field name="position" label="Question position" type="number" value={Math.max(0,...(quiz.questions ?? []).map(q => q.position))+1} />{[1,2,3,4].map(n => <Field key={n} name={`option${n}`} label={`Answer ${n}${n > 2 ? ' (optional)' : ''}`} required={n <= 2} />)}<label>Correct answer<select className={inputClass} name="correct">{[1,2,3,4].map(n => <option key={n} value={n}>Answer {n}</option>)}</select></label></ActionForm>{!quiz.isPublished && <ActionForm label="Publish quiz" onDone={refresh} submit={() => instructorApi.publishQuiz(quiz.id)}><p>At least one question is required.</p></ActionForm>}</details>; }
export function CourseOutline({ course }: { course: Course }) { return <div className="space-y-5">{course.modules?.map(module => <section key={module.id}><h2 className="text-2xl">{module.title}</h2>{module.lessons?.map(lesson => <article className="border p-4" key={lesson.id}><h3>{lesson.title}</h3><p className="whitespace-pre-wrap">{lesson.content}</p>{lesson.videoUrl && <a href={lesson.videoUrl} target="_blank" rel="noreferrer">Open lesson video</a>}</article>)}</section>)}{course.quizzes?.map(quiz => <section key={quiz.id}><h2 className="text-2xl">Quiz: {quiz.title}</h2>{quiz.questions?.map(q => <div className="border p-4" key={q.id}><p>{q.questionText}</p>{q.options.map(o => <p key={o.id}>{o.isCorrect ? "Correct: " : ""}{o.optionText}</p>)}</div>)}</section>)}</div>; }
