import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowRight } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { z } from 'zod';
import { useAuth } from '../context/AuthContext';
import { apiErrorMessage } from '../api/client';
import { useState } from 'react';

const loginSchema = z.object({ email: z.string().email(), password: z.string().min(8) });
const registerSchema = loginSchema.extend({ firstName: z.string().min(1), lastName: z.string().min(1), role: z.enum(['student', 'instructor']) });
type RegisterForm = { firstName: string; lastName: string; email: string; password: string; role: 'student' | 'instructor' };
function Field({ label, error, ...props }: { label: string; error?: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label className="block font-sans text-sm font-bold">{label}<input {...props} className="mt-2 w-full border border-[#c9c1b0] bg-[#fbfaf5] px-4 py-3 font-normal outline-none focus:border-[#d86445]" />{error && <span className="mt-1 block text-xs font-normal text-[#a84732]">{error}</span>}</label>; }
export function LoginPage() { const { login } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [error, setError] = useState(''); const form = useForm<z.infer<typeof loginSchema>>({ resolver: zodResolver(loginSchema) }); return <AuthFrame title="Welcome back" detail="Pick up where your next capability begins."><form className="space-y-5" onSubmit={form.handleSubmit(async (data) => { try { await login(data.email, data.password); navigate((location.state as { from?: string })?.from ?? '/dashboard'); } catch (err) { setError(apiErrorMessage(err)); } })}><Field label="Email" type="email" {...form.register('email')} error={form.formState.errors.email?.message} /><Field label="Password" type="password" {...form.register('password')} error={form.formState.errors.password?.message} />{error && <p className="font-sans text-sm text-[#a84732]">{error}</p>}<Submit>{form.formState.isSubmitting ? 'Signing in...' : 'Sign in'}</Submit></form><p className="mt-6 font-sans text-sm text-[#657066]">New to SkillForge? <Link className="font-bold text-[#d86445]" to="/register">Create an account</Link></p></AuthFrame>; }
export function RegisterPage() { const { register } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(''); const form = useForm<RegisterForm>({ resolver: zodResolver(registerSchema) as never, defaultValues: { role: 'student' } }); return <AuthFrame title="Make your next move" detail="Create a learning account and start building momentum."><form className="space-y-5" onSubmit={form.handleSubmit(async (data) => { try { await register(data); navigate('/dashboard'); } catch (err) { setError(apiErrorMessage(err)); } })}><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" {...form.register('firstName')} error={form.formState.errors.firstName?.message} /><Field label="Last name" {...form.register('lastName')} error={form.formState.errors.lastName?.message} /></div><Field label="Email" type="email" {...form.register('email')} error={form.formState.errors.email?.message} /><Field label="Password" type="password" {...form.register('password')} error={form.formState.errors.password?.message} /><label className="block font-sans text-sm font-bold">I am joining as<select {...form.register('role')} className="mt-2 w-full border border-[#c9c1b0] bg-[#fbfaf5] px-4 py-3 font-normal"><option value="student">Student</option><option value="instructor">Instructor</option></select></label>{error && <p className="font-sans text-sm text-[#a84732]">{error}</p>}<Submit>{form.formState.isSubmitting ? 'Creating account...' : 'Create account'}</Submit></form><p className="mt-6 font-sans text-sm text-[#657066]">Already registered? <Link className="font-bold text-[#d86445]" to="/login">Sign in</Link></p></AuthFrame>; }
function Submit({ children }: { children: React.ReactNode }) { return <button className="flex w-full items-center justify-center gap-2 rounded-full bg-[#d86445] px-5 py-3 font-sans text-sm font-bold text-white hover:bg-[#bb5038]" type="submit">{children}<ArrowRight size={16} /></button>; }
function AuthFrame({ title, detail, children }: { title: string; detail: string; children: React.ReactNode }) { return <div className="grid min-h-[calc(100vh-73px)] lg:grid-cols-2"><div className="hidden bg-[#193b31] p-12 text-white lg:flex lg:flex-col lg:justify-end"><p className="font-sans text-xs uppercase tracking-[.3em] text-[#edbd61]">SkillForge / account</p><h1 className="mt-4 max-w-md text-6xl leading-none">Practice is a form of direction.</h1></div><div className="mx-auto flex w-full max-w-xl flex-col justify-center px-6 py-16"><p className="font-sans text-xs font-bold uppercase tracking-[.25em] text-[#d86445]">Account</p><h1 className="mt-3 text-4xl">{title}</h1><p className="mt-3 font-sans text-sm text-[#657066]">{detail}</p><div className="mt-9">{children}</div></div></div>; }
