import { ArrowRight, Compass, Layers3, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { catalogApi } from '../api/endpoints';
import { CourseCard } from '../components/CourseCard';
import { ErrorState, LoadingState } from '../components/State';

export function HomePage() { const courses = useQuery({ queryKey: ['courses', 'featured'], queryFn: () => catalogApi.courses({ page: 1, limit: 3 }).then((r) => r.data.data) }); return <div>
  <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pt-28"><div><p className="font-sans text-xs font-bold uppercase tracking-[0.3em] text-[#d86445]">A sharper way to grow</p><h1 className="mt-5 max-w-3xl text-6xl leading-[.95] tracking-tight sm:text-7xl">Build skills that hold up in the real world.</h1><p className="mt-7 max-w-xl font-sans text-lg leading-8 text-[#657066]">Focused courses, practical lessons, and a learning path that respects your time. Find the next capability worth mastering.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/courses" className="flex items-center gap-2 rounded-full bg-[#d86445] px-6 py-3 font-sans text-sm font-bold text-white">Explore courses <ArrowRight size={17} /></Link><Link to="/register" className="rounded-full border border-[#a9aa9e] px-6 py-3 font-sans text-sm font-bold">Start learning</Link></div></div><div className="relative min-h-[340px] overflow-hidden bg-[#193b31] p-8 text-white"><div className="absolute -right-12 -top-12 h-48 w-48 rounded-full border-[28px] border-[#edbd61]" /><div className="absolute bottom-0 left-0 h-32 w-32 bg-[#d86445]" /><div className="relative flex h-full flex-col justify-end"><p className="font-sans text-xs uppercase tracking-[.25em] text-[#edbd61]">The forge</p><p className="mt-3 max-w-sm text-4xl leading-tight">Make progress visible. Make it yours.</p><div className="mt-8 flex gap-5 font-sans text-xs text-[#c7d2c7]"><span className="flex items-center gap-2"><Sparkles size={15} /> Applied practice</span><span className="flex items-center gap-2"><Compass size={15} /> Clear direction</span></div></div></div></section>
  <section className="border-y border-[#d8d2c3] bg-[#e9e4d7]"><div className="mx-auto grid max-w-7xl gap-5 px-5 py-7 sm:grid-cols-3 lg:px-8"><div className="flex items-center gap-3"><Layers3 className="text-[#d86445]" /><div><strong className="font-sans text-sm">Structured paths</strong><p className="font-sans text-xs text-[#657066]">Learn in a sequence that makes sense.</p></div></div><div className="flex items-center gap-3"><Compass className="text-[#d86445]" /><div><strong className="font-sans text-sm">Practical focus</strong><p className="font-sans text-xs text-[#657066]">Lessons you can use immediately.</p></div></div><div className="flex items-center gap-3"><Sparkles className="text-[#d86445]" /><div><strong className="font-sans text-sm">Proof of progress</strong><p className="font-sans text-xs text-[#657066]">Track milestones and earn certificates.</p></div></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><div className="mb-8 flex items-end justify-between"><div><p className="font-sans text-xs font-bold uppercase tracking-[.25em] text-[#d86445]">Start here</p><h2 className="mt-2 text-4xl">Featured courses</h2></div><Link to="/courses" className="font-sans text-sm font-bold">Browse all <ArrowRight className="ml-1 inline" size={15} /></Link></div>{courses.isLoading ? <LoadingState /> : courses.isError ? <ErrorState /> : <div className="grid gap-5 md:grid-cols-3">{courses.data?.items.map((course) => <CourseCard key={course.id} course={course} />)}</div>}</section>
</div>; }
